# Generated by Django 5.0.6 on 2024-07-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('content_edit', 'עורך תוכן'), ('add_screen', 'מוסיף מסכים')], default='regular', max_length=100),
        ),
    ]
